// Contract group E — DOM bindings (D2, D3, D4, D9) and C1/C2 fuzz: random
// trees of live bindings, Shows and Fors, checked against a text model after
// every op; disposing the root must leave the container empty and every
// signal at its pre-mount observer count (assessment §9 Phase 1, item 3).
//
// Flags: VINT_FULL=1 turns on the arms that reproduce KNOWN defects the
// Phase 3 rewrite will fix. Those arms — and the explicit reproductions at
// the end — are `test.fails`: vitest passes them only while they throw, so
// a fix forces their promotion to `test`.
import fc from "fast-check"
import { beforeEach, describe, expect, test } from "vitest"
import type { Accessor, Child } from "../src/index"
import { createSignal, For, mount, Show, tags } from "../src/index"
import { __observerCount } from "../src/reactive"
import { FULL } from "./helpers/flags"

/** Arms that reproduce a known defect: off by default, `test.fails` under VINT_FULL. */
// Phase 3 landed: the arms that reproduced H3/M1/L8 are real tests now
const knownDefect = test

const { div, li, span, ul } = tags

let host: HTMLDivElement
beforeEach(() => {
  document.body.innerHTML = ""
  host = document.createElement("div")
  document.body.append(host)
})

// ---------------------------------------------------------------------------
// Tree specs (pure data, generated by fast-check)
// ---------------------------------------------------------------------------

type ForFallback = "plain" | "show" | "accessor" | "array"

type Spec =
  | { kind: "text"; value: string }
  | { kind: "el"; tag: string; children: Spec[] }
  /** A live binding reading one text signal and one boolean signal. */
  | { kind: "bind"; mode: "text" | "el" | "array"; children: Spec[] }
  | { kind: "show"; children: Spec; fallback: Spec | null }
  | { kind: "for"; size: number; fallback: ForFallback }

const TAGS = ["div", "span", "p", "section", "ul"] as const

function specArb(forFallback: fc.Arbitrary<ForFallback>): fc.Arbitrary<Spec> {
  const text: fc.Arbitrary<Spec> = fc
    .constantFrom("a", "b", "-", "x", "")
    .map((value) => ({ kind: "text", value }))
  const forSpec: fc.Arbitrary<Spec> = fc
    .record({ size: fc.integer({ min: 0, max: 4 }), fallback: forFallback })
    .map(({ size, fallback }) => ({ kind: "for", size, fallback }))
  // width ≤ 4 per node, depth ≤ 4 (beyond it only text leaves are drawn);
  // the root is never a bare text so every tree has at least one live part
  const { root } = fc.letrec<{ spec: Spec; root: Spec }>((tie) => {
    const kids = fc.array(tie("spec"), { minLength: 1, maxLength: 4 })
    const el = fc
      .record({ tag: fc.constantFrom(...TAGS), children: kids })
      .map(({ tag, children }): Spec => ({ kind: "el", tag, children }))
    const bind = fc
      .record({ mode: fc.constantFrom("text", "el", "array"), children: kids })
      .map(({ mode, children }): Spec => ({ kind: "bind", mode, children }))
    const show = fc
      .record({ children: tie("spec"), fallback: fc.option(tie("spec"), { nil: null }) })
      .map(({ children, fallback }): Spec => ({ kind: "show", children, fallback }))
    return {
      spec: fc.oneof(
        { maxDepth: 4, depthSize: "max", depthIdentifier: "spec" },
        text,
        el,
        bind,
        show,
        forSpec,
      ),
      root: fc.oneof({ depthIdentifier: "spec" }, el, bind, show, forSpec),
    }
  })
  return root
}

// ---------------------------------------------------------------------------
// Instantiation: signals live OUTSIDE the mount so baselines can be recorded
// ---------------------------------------------------------------------------

type Sig<T> = { get: Accessor<T>; set: (v: T) => void; value: T; baseline: number }

type World = {
  texts: Sig<string>[]
  bools: Sig<boolean>[]
  lists: Sig<number[]>[]
  nextId: number
}

type Inst =
  | { kind: "text"; value: string }
  | { kind: "el"; tag: string; children: Inst[] }
  | { kind: "bind"; mode: "text" | "el" | "array"; t: Sig<string>; b: Sig<boolean>; children: Inst[] }
  | { kind: "show"; b: Sig<boolean>; children: Inst; fallback: Inst | null }
  | { kind: "for"; list: Sig<number[]>; fallback: ForFallback; ft: Sig<string>; fb: Sig<boolean> }

function sig<T>(value: T): Sig<T> {
  const [get, set] = createSignal<T>(value)
  const s: Sig<T> = { get, set: (v) => set(() => v), value, baseline: 0 }
  s.baseline = __observerCount(get)
  return s
}

function instantiate(spec: Spec, w: World): Inst {
  switch (spec.kind) {
    case "text":
      return spec
    case "el":
      return { kind: "el", tag: spec.tag, children: spec.children.map((c) => instantiate(c, w)) }
    case "bind": {
      const t = sig(`t${w.texts.length}`)
      const b = sig(w.bools.length % 2 === 0) // half start hidden: D3 null-first
      w.texts.push(t)
      w.bools.push(b)
      return {
        kind: "bind",
        mode: spec.mode,
        t,
        b,
        children: spec.children.map((c) => instantiate(c, w)),
      }
    }
    case "show": {
      const b = sig(w.bools.length % 2 === 0)
      w.bools.push(b)
      return {
        kind: "show",
        b,
        children: instantiate(spec.children, w),
        fallback: spec.fallback ? instantiate(spec.fallback, w) : null,
      }
    }
    case "for": {
      const list = sig(Array.from({ length: spec.size }, () => w.nextId++))
      const ft = sig(`f${w.texts.length}`)
      const fb = sig(true)
      w.lists.push(list)
      w.texts.push(ft)
      w.bools.push(fb)
      return { kind: "for", list, fallback: spec.fallback, ft, fb }
    }
  }
}

/** Build real DOM for an instance. Called again whenever an enclosing
 *  binding or Show branch rebuilds, so nested signals are re-subscribed
 *  under the new owner every time. */
function build(inst: Inst): Child {
  switch (inst.kind) {
    case "text":
      return inst.value
    case "el":
      return (tags as unknown as Record<string, (...a: unknown[]) => Element>)[inst.tag]!(
        ...inst.children.map(build),
      )
    case "bind": {
      const { t, b, mode, children } = inst
      if (mode === "text") return () => (b.get() ? t.get() : null)
      if (mode === "el") return () => (b.get() ? span(...children.map(build)) : null)
      // D4/D5: an array mixing statics (a string, an element kept across
      // runs) with a nested function
      const kept = tags.b("S")
      return () => (b.get() ? ["(", kept, () => t.get(), ")"] : null)
    }
    case "show": {
      const { b, children, fallback } = inst
      return fallback
        ? Show({ when: b.get, children: () => build(children), fallback: () => build(fallback) })
        : Show({ when: b.get, children: () => build(children) })
    }
    case "for": {
      const { list, ft, fb } = inst
      const fallbacks: Record<ForFallback, () => Child> = {
        plain: () => li("empty"),
        // the three H3 shapes: a fallback whose TOP-LEVEL child is live
        show: () => Show({ when: fb.get, children: () => li("f1"), fallback: () => li("f0") }),
        accessor: () => ft.get,
        array: () => ["<", () => ft.get(), ">"],
      }
      return For({
        each: list.get,
        children: (item) => li(() => `[${item()}]`),
        fallback: fallbacks[inst.fallback],
      })
    }
  }
}

/** The oracle: what `textContent` must be for the current signal values. */
function render(inst: Inst): string {
  switch (inst.kind) {
    case "text":
      return inst.value
    case "el":
      return inst.children.map(render).join("")
    case "bind": {
      if (!inst.b.value) return ""
      if (inst.mode === "text") return inst.t.value
      if (inst.mode === "el") return inst.children.map(render).join("")
      return `(S${inst.t.value})`
    }
    case "show":
      return inst.b.value ? render(inst.children) : inst.fallback ? render(inst.fallback) : ""
    case "for": {
      const { list, fallback, ft, fb } = inst
      if (list.value.length) return list.value.map((n) => `[${n}]`).join("")
      if (fallback === "plain") return "empty"
      if (fallback === "show") return fb.value ? "f1" : "f0"
      if (fallback === "accessor") return ft.value
      return `<${ft.value}>`
    }
  }
}

// ---------------------------------------------------------------------------
// Ops
// ---------------------------------------------------------------------------

type Op = { kind: "flip" | "text" | "list"; i: number; j: number; sub: number }

const opArb: fc.Arbitrary<Op> = fc.record({
  kind: fc.constantFrom("flip", "text", "list"),
  i: fc.nat({ max: 1000 }),
  j: fc.nat({ max: 1000 }),
  sub: fc.nat({ max: 4 }),
})

function applyOp(op: Op, w: World): void {
  if (op.kind === "flip") {
    const b = w.bools[op.i % w.bools.length]
    if (!b) return
    b.value = !b.value
    b.set(b.value)
  } else if (op.kind === "text") {
    const t = w.texts[op.i % w.texts.length]
    if (!t) return
    t.value = `v${op.j}`
    t.set(t.value)
  } else {
    const l = w.lists[op.i % w.lists.length]
    if (!l) return
    const cur = l.value
    let next: number[]
    switch (op.sub) {
      case 0: {
        const at = op.j % (cur.length + 1)
        next = [...cur.slice(0, at), w.nextId++, ...cur.slice(at)]
        break
      }
      case 1:
        next = cur.length ? cur.filter((_, i) => i !== op.j % cur.length) : []
        break
      case 2: {
        // deterministic reorder: rotate by j, then swap the ends
        const k = cur.length ? op.j % cur.length : 0
        next = [...cur.slice(k), ...cur.slice(0, k)]
        if (next.length > 1)
          [next[0], next[next.length - 1]] = [next[next.length - 1] as number, next[0] as number]
        break
      }
      case 3:
        next = []
        break
      default:
        next = Array.from({ length: 1 + (op.j % 4) }, () => w.nextId++)
    }
    if (next.length > 6) next = next.slice(0, 6)
    l.value = next
    l.set(next)
  }
}

function setList(l: Sig<number[]>, next: number[]): void {
  l.value = next
  l.set(next)
}

/** One property run: mount, apply ops, check after each, dispose, check. */
function runTree(spec: Spec, ops: readonly Op[]): void {
  document.body.innerHTML = ""
  host = document.createElement("div")
  document.body.append(host)
  const w: World = { texts: [], bools: [], lists: [], nextId: 10 }
  const inst = instantiate(spec, w)
  const all = [...w.texts, ...w.bools, ...w.lists] as Sig<unknown>[]
  const dispose = mount(host, () => build(inst))
  const check = () => expect(host.textContent).toBe(render(inst))
  check()
  for (const op of ops) {
    applyOp(op, w)
    check()
  }
  // every For goes empty and back twice more — the H3 shape lives here
  for (const l of w.lists) {
    for (let cycle = 0; cycle < 2; cycle++) {
      setList(l, [])
      check()
      setList(l, [w.nextId++, w.nextId++])
      check()
    }
  }
  dispose()
  expect(host.childNodes.length).toBe(0)
  for (const s of all) expect(__observerCount(s.get)).toBe(s.baseline)
}

const opsArb = fc.array(opArb, { minLength: 6, maxLength: 30 })

function fuzz(forFallback: fc.Arbitrary<ForFallback>, seed: number, numRuns: number): void {
  fc.assert(
    fc.property(specArb(forFallback), opsArb, (spec, ops) => {
      runTree(spec, ops)
    }),
    { seed, numRuns, endOnFailure: true },
  )
}

// ---------------------------------------------------------------------------

describe("range fuzz", () => {
  test("E44/D2+D3+D4+D9 random binding trees: text matches the model after every op; dispose leaves nothing", () => {
    fuzz(fc.constant("plain"), 20260904, 150)
  })

  test("E45/C1+C2+D9 the same with a different seed and deeper op sequences", () => {
    fuzz(fc.constant("plain"), 7, 100)
  })

  // Assessment H3: a For fallback whose top-level child is a live binding
  // (Show / bare accessor / array with a function) orphans its nodes when
  // rows appear and on dispose. Promote to `test` once fixed.
  knownDefect("E46/C2+D9 KNOWN(H3) trees whose For fallbacks are live bindings", () => {
    fuzz(fc.constantFrom("show", "accessor", "array"), 20260904, 100)
  })
})

// ---------------------------------------------------------------------------
// Explicit reproductions of the verified defects (assessment §6). Each is
// `test.fails`: it passes only while the defect is present, so the fix that
// lands in Phase 3 will fail these until they are promoted to `test`.
// ---------------------------------------------------------------------------

describe("known defects", () => {
  const liveFallbacks: Array<
    [string, (loading: Accessor<boolean>, text: Accessor<string>) => () => Child]
  > = [
    [
      "a Show",
      (loading) => () =>
        Show({ when: loading, children: () => li("spinner"), fallback: () => li("nothing") }),
    ],
    ["a bare accessor", (_, text) => () => text],
    ["an array with a function", (_, text) => () => [li("["), () => text(), li("]")]],
  ]

  for (const [what, fallback] of liveFallbacks) {
    test(`E47/C2 KNOWN(H3) a For fallback that is ${what} is removed entirely when rows appear`, () => {
      const [items, setItems] = createSignal<string[]>([])
      const [loading] = createSignal(false)
      const [text] = createSignal("nothing")
      mount(host, () =>
        ul(For({ each: items, fallback: fallback(loading, text), children: (i) => li(() => i()) })),
      )
      expect(host.textContent).toBe(what === "an array with a function" ? "[nothing]" : "nothing")
      setItems(["a"])
      // C2: "everything it renders — including content that arrives on a
      // later flush — is removed when the list becomes non-empty"
      expect(host.textContent).toBe("a")
      expect(host.querySelectorAll("li")).toHaveLength(1)
    })
  }

  test("E48/D9 KNOWN(H3) a top-level For with a Show fallback: dispose removes the orphan too", () => {
    const [items, setItems] = createSignal<string[]>([])
    const [loading] = createSignal(false)
    const dispose = mount(host, () =>
      For({
        each: items,
        fallback: () =>
          Show({ when: loading, children: () => li("spinner"), fallback: () => li("nothing") }),
        children: (i) => li(() => i()),
      }),
    )
    setItems(["a"])
    setItems([])
    setItems(["b"])
    dispose()
    // D9: "removes the mounted DOM" is literal
    expect(host.childNodes.length).toBe(0)
  })

  test("E49/D9 KNOWN(M1) a view whose binding throws on its first run leaves nothing subscribed", () => {
    const [n] = createSignal(0)
    expect(() =>
      mount(host, () =>
        div({
          class: () => {
            n() // tracked before the throw
            throw new Error("boom")
          },
        }),
      ),
    ).toThrow("boom")
    // D9: "mount disposes the root, removes anything it appended, and
    // rethrows — nothing stays subscribed"
    expect(__observerCount(n)).toBe(0)
    expect(host.childNodes.length).toBe(0)
  })

  test("E50/D2 KNOWN(L8) a For created outside a binding and returned twice survives the second run", () => {
    const [tick, setTick] = createSignal(0)
    const [list] = createSignal([1, 2])
    mount(host, () => {
      const frag = For({ each: list, children: (item) => span(() => String(item())) })
      return div(() => {
        tick() // an unrelated dependency re-runs the binding
        return frag
      })
    })
    expect(host.textContent).toBe("12")
    setTick(1)
    // D2: "a fragment that an earlier run of the same binding already
    // expanded re-expands to the same nodes when returned again"
    expect(host.textContent).toBe("12")
  })
})
